// Command gen-style-intern generates the exact equality and fingerprint
// functions styleStore uses to intern resolved styles, plus the field list
// that a guard test compares with the live ResolvedStyle fields.
//
// The output lives in internal/layout/style_intern_gen.go. Regenerate from
// that package with:
//
//	go generate ./...
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	// generatedFilePerm is world-readable because the file is generated
	// source, not a secret.
	generatedFilePerm = 0o644

	typeString  = "string"
	typeBool    = "bool"
	typeInt     = "int"
	typeUint64  = "uint64"
	typeFloat64 = "float64"
)

// Sentinel error classes. The generator exits on the first failure, and the
// wrapped detail names the exact type or field that failed.
var (
	errNotFound      = errors.New("not found")
	errUnsupported   = errors.New("unsupported field")
	errNotComparable = errors.New("not comparable")
)

func main() {
	dir := flag.String("dir", ".", "package directory to parse")
	typeName := flag.String("type", "ResolvedStyle", "struct type to generate for")
	out := flag.String("out", "style_intern_gen.go", "generated file name inside dir")
	flag.Parse()

	if err := generate(*dir, *typeName, *out); err != nil {
		fmt.Fprintln(os.Stderr, "gen-style-intern:", err)
		os.Exit(1)
	}
}

// generator walks the parsed package structs and records every named struct
// type that needs a generated hash helper.
type generator struct {
	structs    map[string]*ast.StructType
	helpers    map[string]struct{}
	usesMaps   bool
	usesSlices bool
}

func generate(dir, typeName, out string) error {
	gen, err := parsePackage(dir)
	if err != nil {
		return err
	}

	target, ok := gen.structs[typeName]
	if !ok {
		return fmt.Errorf("%w: struct %s in %s", errNotFound, typeName, dir)
	}

	eqTerms, hashLines, fieldNames, err := gen.fields("a", "b", "s", target)
	if err != nil {
		return err
	}

	formatted, err := gen.render(eqTerms, hashLines, fieldNames)
	if err != nil {
		return err
	}

	dest := outputPath(dir, out)
	if err := os.WriteFile(dest, formatted, generatedFilePerm); err != nil {
		return fmt.Errorf("write %s: %w", dest, err)
	}

	return nil
}

// parsePackage parses dir's non-test Go files and indexes every named struct
// type. Test files are skipped so fixtures cannot shadow production types.
func parsePackage(dir string) (*generator, error) {
	gen := &generator{
		structs:    map[string]*ast.StructType{},
		helpers:    map[string]struct{}{},
		usesMaps:   false,
		usesSlices: false,
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read dir %s: %w", dir, err)
	}

	fset := token.NewFileSet()

	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}

		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, 0)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", name, err)
		}

		collectStructs(gen, file)
	}

	return gen, nil
}

func collectStructs(gen *generator, file *ast.File) {
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			if structType, ok := typeSpec.Type.(*ast.StructType); ok {
				gen.structs[typeSpec.Name.Name] = structType
			}
		}
	}
}

// render emits the generated file and gofmts it. Unformatted output is never
// written.
func (g *generator) render(eqTerms, hashLines, fieldNames []string) ([]byte, error) {
	var buf bytes.Buffer

	g.renderHeader(&buf)
	buf.WriteString(primitiveHelpers)
	renderEqual(&buf, eqTerms)
	renderFingerprint(&buf, hashLines)
	renderFields(&buf, fieldNames)

	if err := g.writeStructHelpers(&buf); err != nil {
		return nil, err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w\n%s", err, buf.String())
	}

	return formatted, nil
}

func (g *generator) renderHeader(buf *bytes.Buffer) {
	buf.WriteString("// Code generated by scripts/gen-style-intern; DO NOT EDIT.\n\n")
	buf.WriteString("package layout\n\n")
	buf.WriteString("import (\n\t\"math\"\n")

	if g.usesMaps {
		buf.WriteString("\t\"maps\"\n")
	}

	if g.usesSlices {
		buf.WriteString("\t\"slices\"\n")
	}

	buf.WriteString(")\n\n")

	buf.WriteString("// styleInternSeed and styleInternPrime are the FNV-1a 64 offset and prime.\n")
	buf.WriteString("const (\n\tstyleInternSeed  = uint64(14695981039346656037)\n")
	buf.WriteString("\tstyleInternPrime = uint64(1099511628211)\n)\n\n")
}

func renderEqual(buf *bytes.Buffer, eqTerms []string) {
	buf.WriteString("// styleInternEqual reports exact semantic equality of two stored styles.\n")
	buf.WriteString("// It compares every ResolvedStyle field, slice, and map by value.\n")
	buf.WriteString("func styleInternEqual(a, b *ResolvedStyle) bool {\n")
	buf.WriteString("\tif a == b {\n\t\treturn true\n\t}\n\n")
	buf.WriteString("\treturn ")

	for i, term := range eqTerms {
		if i > 0 {
			buf.WriteString(" &&\n\t\t")
		}

		buf.WriteString(term)
	}

	buf.WriteString("\n}\n\n")
}

func renderFingerprint(buf *bytes.Buffer, hashLines []string) {
	buf.WriteString("// styleInternFingerprint hashes every ResolvedStyle field. Equal styles\n")
	buf.WriteString("// share a fingerprint; collisions are resolved by styleInternEqual.\n")
	buf.WriteString("func styleInternFingerprint(s *ResolvedStyle) uint64 {\n\th := styleInternSeed\n")

	for _, line := range hashLines {
		buf.WriteString("\t" + line + "\n")
	}

	buf.WriteString("\n\treturn h\n}\n\n")
}

func renderFields(buf *bytes.Buffer, fieldNames []string) {
	buf.WriteString("// styleInternFields lists every field styleInternEqual and\n")
	buf.WriteString("// styleInternFingerprint cover, in declaration order.\n")
	buf.WriteString("func styleInternFields() []string {\n\treturn []string{\n")

	for _, name := range fieldNames {
		buf.WriteString("\t\t\"" + name + "\",\n")
	}

	buf.WriteString("\t}\n}\n\n")
}

// outputPath resolves out against dir unless out already names a path.
func outputPath(dir, out string) string {
	if strings.HasPrefix(out, string(os.PathSeparator)) || strings.HasPrefix(out, ".") {
		return out
	}

	return dir + string(os.PathSeparator) + out
}

// fields classifies one struct's fields. eqA/eqB name the equality operands,
// hashVar names the fingerprint receiver.
func (g *generator) fields(eqA, eqB, hashVar string, st *ast.StructType) ([]string, []string, []string, error) {
	eqTerms := make([]string, 0, len(st.Fields.List))
	hashLines := make([]string, 0, len(st.Fields.List))
	fieldNames := make([]string, 0, len(st.Fields.List))

	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			return nil, nil, nil, fmt.Errorf("%w: embedded field %v", errUnsupported, field.Type)
		}

		for _, name := range field.Names {
			eq, hash, err := g.classify(eqA+"."+name.Name, eqB+"."+name.Name, hashVar+"."+name.Name, field.Type)
			if err != nil {
				return nil, nil, nil, err
			}

			eqTerms = append(eqTerms, eq)
			hashLines = append(hashLines, hash...)
			fieldNames = append(fieldNames, name.Name)
		}
	}

	return eqTerms, hashLines, fieldNames, nil
}

// classify returns the equality term and fingerprint statements for one
// field type. Unsupported types fail generation instead of being skipped.
func (g *generator) classify(eqA, eqB, hashVar string, expr ast.Expr) (string, []string, error) {
	switch expr := expr.(type) {
	case *ast.Ident:
		return g.classifyIdent(eqA, eqB, hashVar, expr.Name)
	case *ast.ArrayType:
		return g.classifyArray(eqA, eqB, hashVar, expr)
	case *ast.MapType:
		return g.classifyMap(eqA, eqB, hashVar, expr)
	default:
		return "", nil, fmt.Errorf("%w: type %v", errUnsupported, expr)
	}
}

func (g *generator) classifyArray(eqA, eqB, hashVar string, expr *ast.ArrayType) (string, []string, error) {
	if expr.Len == nil {
		return g.classifySlice(eqA, eqB, hashVar, expr)
	}

	if !g.comparable(expr.Elt) {
		return "", nil, fmt.Errorf("%w: array element %v", errNotComparable, expr.Elt)
	}

	return eqA + " == " + eqB, []string{
		"for _, e := range " + hashVar + " {\n\t\th = " + g.hashCall(expr.Elt) + "\n\t}",
	}, nil
}

func (g *generator) classifyMap(eqA, eqB, hashVar string, expr *ast.MapType) (string, []string, error) {
	key, keyIsIdent := expr.Key.(*ast.Ident)
	if !keyIsIdent || key.Name != typeString {
		return "", nil, fmt.Errorf("%w: map key %v", errUnsupported, expr.Key)
	}

	value, valueIsIdent := expr.Value.(*ast.Ident)
	if !valueIsIdent || value.Name != typeString {
		return "", nil, fmt.Errorf("%w: map value %v", errUnsupported, expr.Value)
	}

	g.usesMaps = true

	return "maps.Equal(" + eqA + ", " + eqB + ")", []string{
		"h = styleInternHashStringMap(h, " + hashVar + ")",
	}, nil
}

func (g *generator) classifyIdent(eqA, eqB, hashVar, name string) (string, []string, error) {
	if hashFunc, isPrimitive := primitiveHashFunc(name); isPrimitive {
		return eqA + " == " + eqB, []string{"h = " + hashFunc + "(h, " + hashVar + ")"}, nil
	}

	if _, ok := g.structs[name]; !ok {
		return "", nil, fmt.Errorf("%w: identifier type %q", errUnsupported, name)
	}

	if !g.comparable(identNamed(name)) {
		return "", nil, fmt.Errorf("%w: struct %s", errNotComparable, name)
	}

	g.helpers[name] = struct{}{}

	return eqA + " == " + eqB, []string{
		"h = " + helperName(name) + "(h, " + hashVar + ")",
	}, nil
}

// primitiveHashFunc maps a basic type name to its generated hash function.
func primitiveHashFunc(name string) (string, bool) {
	switch name {
	case typeString:
		return "styleInternHashString", true
	case typeBool:
		return "styleInternHashBool", true
	case typeInt:
		return "styleInternHashInt", true
	case typeUint64:
		return "styleInternHashUint64", true
	case typeFloat64:
		return "styleInternHashFloat64", true
	default:
		return "", false
	}
}

func (g *generator) classifySlice(eqA, eqB, hashVar string, expr *ast.ArrayType) (string, []string, error) {
	elem, elemIsIdent := expr.Elt.(*ast.Ident)
	if !elemIsIdent {
		return "", nil, fmt.Errorf("%w: slice element %v", errUnsupported, expr.Elt)
	}

	g.usesSlices = true

	switch elem.Name {
	case typeString:
		return "slices.Equal(" + eqA + ", " + eqB + ")", []string{
			"h = styleInternHashStringSlice(h, " + hashVar + ")",
		}, nil
	case typeFloat64:
		return "slices.Equal(" + eqA + ", " + eqB + ")", []string{
			"h = styleInternHashFloat64Slice(h, " + hashVar + ")",
		}, nil
	default:
		return "", nil, fmt.Errorf("%w: slice element %q", errUnsupported, elem.Name)
	}
}

// hashCall returns the fingerprint expression for one array element named e.
func (g *generator) hashCall(expr ast.Expr) string {
	elem, elemIsIdent := expr.(*ast.Ident)
	if !elemIsIdent {
		panic(fmt.Sprintf("hashCall: unsupported element type %v", expr))
	}

	if hashFunc, isPrimitive := primitiveHashFunc(elem.Name); isPrimitive {
		return hashFunc + "(h, e)"
	}

	if g.comparable(elem) {
		g.helpers[elem.Name] = struct{}{}

		return helperName(elem.Name) + "(h, e)"
	}

	panic(fmt.Sprintf("hashCall: unsupported element type %v", expr))
}

// comparable reports whether a type can use ==, recursing through arrays and
// named structs declared in the same package.
func (g *generator) comparable(expr ast.Expr) bool {
	switch expr := expr.(type) {
	case *ast.Ident:
		if _, isPrimitive := primitiveHashFunc(expr.Name); isPrimitive {
			return true
		}

		st, ok := g.structs[expr.Name]
		if !ok {
			return false
		}

		for _, field := range st.Fields.List {
			if !g.comparable(field.Type) {
				return false
			}
		}

		return true
	case *ast.ArrayType:
		return g.comparable(expr.Elt)
	default:
		return false
	}
}

// writeStructHelpers emits one hash helper per referenced named struct type.
func (g *generator) writeStructHelpers(buf *bytes.Buffer) error {
	names := make([]string, 0, len(g.helpers))

	for name := range g.helpers {
		names = append(names, name)
	}

	sort.Strings(names)

	for _, name := range names {
		structType, ok := g.structs[name]
		if !ok {
			return fmt.Errorf("%w: helper struct %q", errNotFound, name)
		}

		if !g.comparable(identNamed(name)) {
			return fmt.Errorf("%w: struct %q", errNotComparable, name)
		}

		buf.WriteString("func " + helperName(name) + "(h uint64, v " + name + ") uint64 {\n")

		for _, field := range structType.Fields.List {
			for _, fieldName := range field.Names {
				_, hash, err := g.classify(fieldName.Name, fieldName.Name, "v."+fieldName.Name, field.Type)
				if err != nil {
					return fmt.Errorf("struct %s field %s: %w", name, fieldName.Name, err)
				}

				for _, line := range hash {
					buf.WriteString("\t" + line + "\n")
				}
			}
		}

		buf.WriteString("\n\treturn h\n}\n\n")
	}

	return nil
}

func helperName(typeName string) string {
	if typeName == "" {
		return "styleInternHash"
	}

	return "styleInternHash" + strings.ToUpper(typeName[:1]) + typeName[1:]
}

// identNamed returns the type identifier syntax used by comparability checks.
func identNamed(name string) *ast.Ident {
	return &ast.Ident{NamePos: token.NoPos, Name: name, Obj: nil}
}

// primitiveHelpers are stable primitives shared by every generated helper.
//
// The fingerprint is only a bucket key: styleInternEqual makes the sharing
// decision, so primitives mix in one multiply instead of a full byte loop.
const primitiveHelpers = `func styleInternHashString(h uint64, v string) uint64 {
	h = (h ^ uint64(len(v))) * styleInternPrime

	for i := 0; i < len(v); i++ {
		h = (h ^ uint64(v[i])) * styleInternPrime
	}

	return h
}

func styleInternHashBool(h uint64, v bool) uint64 {
	if v {
		return (h ^ 1) * styleInternPrime
	}

	return (h ^ 0) * styleInternPrime
}

func styleInternHashInt(h uint64, v int) uint64 {
	return (h ^ uint64(v)) * styleInternPrime
}

func styleInternHashUint64(h uint64, v uint64) uint64 {
	return (h ^ v) * styleInternPrime
}

// styleInternFloatBits collapses -0.0 onto +0.0 because the two compare equal
// with == and must share a fingerprint.
func styleInternFloatBits(v float64) uint64 {
	if v == 0 {
		return 0
	}

	return math.Float64bits(v)
}

func styleInternHashFloat64(h uint64, v float64) uint64 {
	return (h ^ styleInternFloatBits(v)) * styleInternPrime
}

func styleInternHashStringSlice(h uint64, vs []string) uint64 {
	h = (h ^ uint64(len(vs))) * styleInternPrime

	for _, v := range vs {
		h = styleInternHashString(h, v)
	}

	return h
}

func styleInternHashFloat64Slice(h uint64, vs []float64) uint64 {
	h = (h ^ uint64(len(vs))) * styleInternPrime

	for _, v := range vs {
		h = styleInternHashFloat64(h, v)
	}

	return h
}

func styleInternHashStringMap(h uint64, m map[string]string) uint64 {
	if m == nil {
		return (h ^ 0) * styleInternPrime
	}

	var acc uint64

	for k, v := range m {
		acc ^= styleInternHashString(styleInternHashString(styleInternSeed, k), v)
	}

	return (h ^ uint64(len(m))) * styleInternPrime ^ acc
}

`
