package fixturetests

import "testing"

// TestOutputFixture01SimpleInvoice checks the first committed sample against
// a fresh conversion: every text run, rule, and box must land in the same
// place with the same color, and the authored features below must be present
// in the committed PDF.
//
// Ground truth measured with scripts/inspect_pdf_ops.py (PyMuPDF 1.27.1):
//
//	title  "Acme Widgets GmbH"   #1a3d6d at (28.346, 796.503), 18pt bold
//	meta   "Invoice No. 2024-0001" #222222 at (28.346, 752.677), 10pt bold
//	body   "Widget A (standard)" #222222 at (29.096, 697.273), 10pt
//	total  "Total: 234.40 EUR"   #222222 at (482.461, 643.077), 10pt bold
//	footer "Generated by ..."    #888888 at (28.346, 573.470), 8pt
//	rule   #cccccc 0.75pt from (28.721, 594.169) to (566.559, 594.169)
//	no images, no filled boxes, A4 595.28 x 841.89
func TestOutputFixture01SimpleInvoice(t *testing.T) {
	t.Parallel()

	committed := readCommittedOps(t, "fixture-01-simple-invoice.pdf")
	fresh := freshOps(t, "fixture-01-simple-invoice.html")

	assertPageOpsMatch(t, committed, fresh)

	titleBlue := [3]float64{26.0 / 255, 61.0 / 255, 109.0 / 255}
	ink := [3]float64{34.0 / 255, 34.0 / 255, 34.0 / 255}
	footerGray := [3]float64{136.0 / 255, 136.0 / 255, 136.0 / 255}

	assertOpsTextRun(t, committed, 1, "Acme Widgets GmbH", 28.346, 796.503, 18, "LiberationSans-Bold", titleBlue)
	assertOpsTextRun(t, committed, 1, "Invoice No. 2024-0001", 28.346, 752.677, 10, "LiberationSans-Bold", ink)
	assertOpsTextRun(t, committed, 1, "Widget A (standard)", 29.096, 697.273, 10, "LiberationSans-Regular", ink)
	assertOpsTextRun(t, committed, 1, "Total: 234.40 EUR", 482.461, 643.077, 10, "LiberationSans-Bold", ink)
	assertOpsTextRun(t, committed, 1, "Generated by gowkhtmltopdf golden fixture 01 - simple invoice.",
		28.346, 573.470, 8, "LiberationSans-Regular", footerGray)

	assertOpsStrokeSegment(t, committed, 1, 28.721, 594.169, 566.559, 594.169, [3]float64{0.8, 0.8, 0.8}, 0.75)

	if committed.Pages != 1 {
		t.Errorf("pages = %d, want 1", committed.Pages)
	}

	// Counts measured with the same tool run: 23 spans, one stroked rule.
	if len(committed.Texts) != 23 {
		t.Errorf("text runs = %d, want 23", len(committed.Texts))
	}

	if len(committed.Strokes) != 1 {
		t.Errorf("strokes = %d, want 1", len(committed.Strokes))
	}

	if len(committed.MediaBoxes) != 1 || !opsBoxClose(committed.MediaBoxes[0], [4]float64{0, 0, 595.28, 841.89}) {
		t.Errorf("mediaboxes = %v, want [[0 0 595.28 841.89]]", committed.MediaBoxes)
	}

	if len(committed.Images) != 0 {
		t.Errorf("images = %d, want 0", len(committed.Images))
	}

	if len(committed.Fills) != 0 {
		t.Errorf("fills = %d, want 0", len(committed.Fills))
	}
}
