// Code generated by scripts/gen-style-intern; DO NOT EDIT.

package layout

import (
	"maps"
	"math"
	"slices"
)

// styleInternSeed and styleInternPrime are the FNV-1a 64 offset and prime.
const (
	styleInternSeed  = uint64(14695981039346656037)
	styleInternPrime = uint64(1099511628211)
)

func styleInternHashString(h uint64, v string) uint64 {
	h = (h ^ uint64(len(v))) * styleInternPrime

	for i := 0; i < len(v); i++ {
		h = (h ^ uint64(v[i])) * styleInternPrime
	}

	return h
}

func styleInternHashBool(h uint64, v bool) uint64 {
	if v {
		return (h ^ 1) * styleInternPrime
	}

	return (h ^ 0) * styleInternPrime
}

func styleInternHashInt(h uint64, v int) uint64 {
	return (h ^ uint64(v)) * styleInternPrime
}

func styleInternHashUint64(h uint64, v uint64) uint64 {
	return (h ^ v) * styleInternPrime
}

// styleInternFloatBits collapses -0.0 onto +0.0 because the two compare equal
// with == and must share a fingerprint.
func styleInternFloatBits(v float64) uint64 {
	if v == 0 {
		return 0
	}

	return math.Float64bits(v)
}

func styleInternHashFloat64(h uint64, v float64) uint64 {
	return (h ^ styleInternFloatBits(v)) * styleInternPrime
}

func styleInternHashStringSlice(h uint64, vs []string) uint64 {
	h = (h ^ uint64(len(vs))) * styleInternPrime

	for _, v := range vs {
		h = styleInternHashString(h, v)
	}

	return h
}

func styleInternHashFloat64Slice(h uint64, vs []float64) uint64 {
	h = (h ^ uint64(len(vs))) * styleInternPrime

	for _, v := range vs {
		h = styleInternHashFloat64(h, v)
	}

	return h
}

func styleInternHashStringMap(h uint64, m map[string]string) uint64 {
	if m == nil {
		return (h ^ 0) * styleInternPrime
	}

	var acc uint64

	for k, v := range m {
		acc ^= styleInternHashString(styleInternHashString(styleInternSeed, k), v)
	}

	return (h^uint64(len(m)))*styleInternPrime ^ acc
}

// styleInternEqual reports exact semantic equality of two stored styles.
// It compares every ResolvedStyle field, slice, and map by value.
func styleInternEqual(a, b *ResolvedStyle) bool {
	if a == b {
		return true
	}

	return a.Display == b.Display &&
		a.IsWebkitBox == b.IsWebkitBox &&
		a.Position == b.Position &&
		a.Float == b.Float &&
		a.Clear == b.Clear &&
		a.BoxSizing == b.BoxSizing &&
		a.Top == b.Top &&
		a.Right == b.Right &&
		a.Bottom == b.Bottom &&
		a.Left == b.Left &&
		a.TopAuto == b.TopAuto &&
		a.RightAuto == b.RightAuto &&
		a.BottomAuto == b.BottomAuto &&
		a.LeftAuto == b.LeftAuto &&
		a.FlexDirection == b.FlexDirection &&
		a.FlexWrap == b.FlexWrap &&
		a.JustifyContent == b.JustifyContent &&
		a.AlignItems == b.AlignItems &&
		a.AlignContent == b.AlignContent &&
		a.AlignSelf == b.AlignSelf &&
		a.JustifyItems == b.JustifyItems &&
		a.JustifySelf == b.JustifySelf &&
		a.Gap == b.Gap &&
		a.RowGap == b.RowGap &&
		a.ColumnGap == b.ColumnGap &&
		a.ColumnGapNormal == b.ColumnGapNormal &&
		a.ColumnCount == b.ColumnCount &&
		a.ColumnWidth == b.ColumnWidth &&
		a.ColumnSpan == b.ColumnSpan &&
		a.ColumnFill == b.ColumnFill &&
		a.ColumnRuleWidth == b.ColumnRuleWidth &&
		a.ColumnRuleStyle == b.ColumnRuleStyle &&
		a.ColumnRuleColor == b.ColumnRuleColor &&
		a.ColumnRuleColorSet == b.ColumnRuleColorSet &&
		a.FlexGrow == b.FlexGrow &&
		a.FlexShrink == b.FlexShrink &&
		a.FlexBasis == b.FlexBasis &&
		a.FlexBasisPercent == b.FlexBasisPercent &&
		a.FlexOrder == b.FlexOrder &&
		a.ZIndex == b.ZIndex &&
		a.ZIndexSet == b.ZIndexSet &&
		a.WritingMode == b.WritingMode &&
		a.Direction == b.Direction &&
		a.Filter == b.Filter &&
		a.MixBlendMode == b.MixBlendMode &&
		a.BackgroundBlendMode == b.BackgroundBlendMode &&
		a.Isolation == b.Isolation &&
		a.GridTemplateColumns == b.GridTemplateColumns &&
		a.GridTemplateRows == b.GridTemplateRows &&
		a.GridTemplateAreas == b.GridTemplateAreas &&
		a.GridArea == b.GridArea &&
		a.GridAutoFlow == b.GridAutoFlow &&
		a.GridAutoColumns == b.GridAutoColumns &&
		a.GridAutoRows == b.GridAutoRows &&
		a.GridColumnSpan == b.GridColumnSpan &&
		a.GridColumnStart == b.GridColumnStart &&
		a.GridRowSpan == b.GridRowSpan &&
		a.GridRowStart == b.GridRowStart &&
		a.Width == b.Width &&
		a.WidthPercent == b.WidthPercent &&
		a.Height == b.Height &&
		a.HeightPercent == b.HeightPercent &&
		a.MinWidth == b.MinWidth &&
		a.MinWidthPercent == b.MinWidthPercent &&
		a.MinWidthSet == b.MinWidthSet &&
		a.MaxWidth == b.MaxWidth &&
		a.MaxWidthPercent == b.MaxWidthPercent &&
		a.MinHeight == b.MinHeight &&
		a.MinHeightPercent == b.MinHeightPercent &&
		a.MaxHeight == b.MaxHeight &&
		a.MaxHeightPercent == b.MaxHeightPercent &&
		a.Overflow == b.Overflow &&
		a.OverflowX == b.OverflowX &&
		a.OverflowY == b.OverflowY &&
		a.Visibility == b.Visibility &&
		a.MarginTop == b.MarginTop &&
		a.MarginRight == b.MarginRight &&
		a.MarginBottom == b.MarginBottom &&
		a.MarginLeft == b.MarginLeft &&
		a.MarginTopAuto == b.MarginTopAuto &&
		a.MarginBottomAuto == b.MarginBottomAuto &&
		a.MarginLeftAuto == b.MarginLeftAuto &&
		a.MarginRightAuto == b.MarginRightAuto &&
		a.PaddingTop == b.PaddingTop &&
		a.PaddingRight == b.PaddingRight &&
		a.PaddingBottom == b.PaddingBottom &&
		a.PaddingLeft == b.PaddingLeft &&
		a.BorderTop == b.BorderTop &&
		a.BorderRight == b.BorderRight &&
		a.BorderBottom == b.BorderBottom &&
		a.BorderLeft == b.BorderLeft &&
		a.BorderRadius == b.BorderRadius &&
		a.BorderRadiusPercent == b.BorderRadiusPercent &&
		a.BorderRadiusTopLeft == b.BorderRadiusTopLeft &&
		a.BorderRadiusTopRight == b.BorderRadiusTopRight &&
		a.BorderRadiusBottomRight == b.BorderRadiusBottomRight &&
		a.BorderRadiusBottomLeft == b.BorderRadiusBottomLeft &&
		a.BorderRadiusTopLeftY == b.BorderRadiusTopLeftY &&
		a.BorderRadiusTopRightY == b.BorderRadiusTopRightY &&
		a.BorderRadiusBottomRightY == b.BorderRadiusBottomRightY &&
		a.BorderRadiusBottomLeftY == b.BorderRadiusBottomLeftY &&
		a.Color == b.Color &&
		a.BGColor == b.BGColor &&
		a.AccentColor == b.AccentColor &&
		a.AccentColorSet == b.AccentColorSet &&
		slices.Equal(a.FontFamily, b.FontFamily) &&
		a.famHash == b.famHash &&
		a.FontSize == b.FontSize &&
		a.FontWeight == b.FontWeight &&
		a.FontItalic == b.FontItalic &&
		a.LineHeight == b.LineHeight &&
		a.LineHeightUnitless == b.LineHeightUnitless &&
		a.TextAlign == b.TextAlign &&
		a.TextAlignLast == b.TextAlignLast &&
		a.TextTransform == b.TextTransform &&
		a.VerticalAlign == b.VerticalAlign &&
		a.VerticalAlignShift == b.VerticalAlignShift &&
		a.WhiteSpace == b.WhiteSpace &&
		a.WhiteSpaceCollapse == b.WhiteSpaceCollapse &&
		a.WhiteSpaceTrim == b.WhiteSpaceTrim &&
		a.TextWrap == b.TextWrap &&
		a.TextWrapMode == b.TextWrapMode &&
		a.TextWrapStyle == b.TextWrapStyle &&
		a.TabSize == b.TabSize &&
		a.Hyphens == b.Hyphens &&
		a.HyphenateCharacter == b.HyphenateCharacter &&
		a.TextJustify == b.TextJustify &&
		a.LineBreak == b.LineBreak &&
		a.OverflowWrap == b.OverflowWrap &&
		a.WordBreak == b.WordBreak &&
		a.TextDecoration == b.TextDecoration &&
		a.TextDecorationLine == b.TextDecorationLine &&
		a.TextDecorationColor == b.TextDecorationColor &&
		a.TextDecorationColorSet == b.TextDecorationColorSet &&
		a.TextDecorationStyle == b.TextDecorationStyle &&
		a.TextDecorationThickness == b.TextDecorationThickness &&
		a.TextUnderlineOffset == b.TextUnderlineOffset &&
		a.TextUnderlinePosition == b.TextUnderlinePosition &&
		a.TextShadowX == b.TextShadowX &&
		a.TextShadowY == b.TextShadowY &&
		a.TextShadowBlur == b.TextShadowBlur &&
		a.TextShadowColor == b.TextShadowColor &&
		a.TextShadowSet == b.TextShadowSet &&
		a.LetterSpacing == b.LetterSpacing &&
		a.WordSpacing == b.WordSpacing &&
		a.TextIndent == b.TextIndent &&
		a.ListStyleType == b.ListStyleType &&
		a.BorderCollapse == b.BorderCollapse &&
		a.BorderSpacing == b.BorderSpacing &&
		a.BorderSpacingV == b.BorderSpacingV &&
		a.TableLayout == b.TableLayout &&
		a.CaptionSide == b.CaptionSide &&
		a.IsReplaced == b.IsReplaced &&
		a.PageBreakBefore == b.PageBreakBefore &&
		a.PageBreakAfter == b.PageBreakAfter &&
		a.PageBreakInside == b.PageBreakInside &&
		a.MarginBreak == b.MarginBreak &&
		a.PageName == b.PageName &&
		a.Orphans == b.Orphans &&
		a.Widows == b.Widows &&
		a.EmptyCells == b.EmptyCells &&
		a.ContainerType == b.ContainerType &&
		a.ContainerName == b.ContainerName &&
		a.Transform == b.Transform &&
		a.HasTransform == b.HasTransform &&
		a.TransformOrigin == b.TransformOrigin &&
		a.TranslateXPercent == b.TranslateXPercent &&
		a.TranslateXPercentSet == b.TranslateXPercentSet &&
		a.TranslateYPercent == b.TranslateYPercent &&
		a.TranslateYPercentSet == b.TranslateYPercentSet &&
		a.Opacity == b.Opacity &&
		a.Content == b.Content &&
		a.GridColumnEnd == b.GridColumnEnd &&
		a.GridRowEnd == b.GridRowEnd &&
		a.OutlineWidth == b.OutlineWidth &&
		a.OutlineStyle == b.OutlineStyle &&
		a.OutlineColor == b.OutlineColor &&
		a.OutlineColorSet == b.OutlineColorSet &&
		a.OutlineOffset == b.OutlineOffset &&
		a.BackgroundImage == b.BackgroundImage &&
		a.BackgroundPosX == b.BackgroundPosX &&
		a.BackgroundPosY == b.BackgroundPosY &&
		a.BackgroundSize == b.BackgroundSize &&
		a.BackgroundRepeat == b.BackgroundRepeat &&
		a.BackgroundRepeatX == b.BackgroundRepeatX &&
		a.BackgroundRepeatY == b.BackgroundRepeatY &&
		a.BackgroundRepeatBlock == b.BackgroundRepeatBlock &&
		a.BackgroundRepeatInline == b.BackgroundRepeatInline &&
		a.BackgroundClip == b.BackgroundClip &&
		a.BackgroundOrigin == b.BackgroundOrigin &&
		a.BackgroundAttachment == b.BackgroundAttachment &&
		a.BorderImageSource == b.BorderImageSource &&
		a.BorderImageSlice == b.BorderImageSlice &&
		a.BorderImageWidth == b.BorderImageWidth &&
		a.BorderImageOutset == b.BorderImageOutset &&
		a.BorderImageRepeat == b.BorderImageRepeat &&
		a.ListStylePosition == b.ListStylePosition &&
		a.QuotesRaw == b.QuotesRaw &&
		a.QuotesOpen == b.QuotesOpen &&
		a.QuotesClose == b.QuotesClose &&
		a.CounterReset == b.CounterReset &&
		a.CounterIncrement == b.CounterIncrement &&
		a.ListStyleImage == b.ListStyleImage &&
		a.BoxShadowX == b.BoxShadowX &&
		a.BoxShadowY == b.BoxShadowY &&
		a.BoxShadowBlur == b.BoxShadowBlur &&
		a.BoxShadowSpread == b.BoxShadowSpread &&
		a.BoxShadowColor == b.BoxShadowColor &&
		a.BoxShadowSet == b.BoxShadowSet &&
		a.BoxShadowInset == b.BoxShadowInset &&
		a.BoxShadowRaw == b.BoxShadowRaw &&
		a.Fill == b.Fill &&
		a.FillSet == b.FillSet &&
		a.FillOpacity == b.FillOpacity &&
		a.Stroke == b.Stroke &&
		a.StrokeSet == b.StrokeSet &&
		a.StrokeWidth == b.StrokeWidth &&
		a.StrokeWidthSet == b.StrokeWidthSet &&
		a.StrokeOpacity == b.StrokeOpacity &&
		slices.Equal(a.StrokeDashArray, b.StrokeDashArray) &&
		a.StrokeDashOffset == b.StrokeDashOffset &&
		a.StrokeLineCap == b.StrokeLineCap &&
		a.StrokeLineJoin == b.StrokeLineJoin &&
		a.StrokeMiterLimit == b.StrokeMiterLimit &&
		a.TextOverflow == b.TextOverflow &&
		a.LineClamp == b.LineClamp &&
		a.MaxLines == b.MaxLines &&
		a.MarginTrim == b.MarginTrim &&
		a.BoxDecorationBreak == b.BoxDecorationBreak &&
		a.TextDecorationSkipInk == b.TextDecorationSkipInk &&
		a.OverflowClipMarginTop == b.OverflowClipMarginTop &&
		a.OverflowClipMarginRight == b.OverflowClipMarginRight &&
		a.OverflowClipMarginBottom == b.OverflowClipMarginBottom &&
		a.OverflowClipMarginLeft == b.OverflowClipMarginLeft &&
		a.Contain == b.Contain &&
		a.ContainIntrinsicWidth == b.ContainIntrinsicWidth &&
		a.ContainIntrinsicHeight == b.ContainIntrinsicHeight &&
		a.ContainIntrinsicBlockSize == b.ContainIntrinsicBlockSize &&
		a.ContainIntrinsicInlineSize == b.ContainIntrinsicInlineSize &&
		a.ContentVisibility == b.ContentVisibility &&
		a.ColorAdjust == b.ColorAdjust &&
		a.ForcedColorAdjust == b.ForcedColorAdjust &&
		a.ColorScheme == b.ColorScheme &&
		a.DynamicRangeLimit == b.DynamicRangeLimit &&
		a.FontLanguageOverride == b.FontLanguageOverride &&
		a.FontOpticalSizing == b.FontOpticalSizing &&
		a.FontPalette == b.FontPalette &&
		a.FontVariationSettings == b.FontVariationSettings &&
		a.ImageOrientation == b.ImageOrientation &&
		a.ImageOrientationAngle == b.ImageOrientationAngle &&
		a.ImageResolution == b.ImageResolution &&
		a.ImageResolutionDPI == b.ImageResolutionDPI &&
		a.ObjectViewBox == b.ObjectViewBox &&
		a.TextCombineUpright == b.TextCombineUpright &&
		a.TextDecorationInset == b.TextDecorationInset &&
		a.TextDecorationSkip == b.TextDecorationSkip &&
		a.TextDecorationSkipBox == b.TextDecorationSkipBox &&
		a.TextDecorationSkipSelf == b.TextDecorationSkipSelf &&
		a.TextDecorationSkipSpaces == b.TextDecorationSkipSpaces &&
		a.TextOrientation == b.TextOrientation &&
		a.UnicodeBidi == b.UnicodeBidi &&
		maps.Equal(a.CustomProps, b.CustomProps)
}

// styleInternFingerprint hashes every ResolvedStyle field. Equal styles
// share a fingerprint; collisions are resolved by styleInternEqual.
func styleInternFingerprint(s *ResolvedStyle) uint64 {
	h := styleInternSeed
	h = styleInternHashString(h, s.Display)
	h = styleInternHashBool(h, s.IsWebkitBox)
	h = styleInternHashString(h, s.Position)
	h = styleInternHashString(h, s.Float)
	h = styleInternHashString(h, s.Clear)
	h = styleInternHashString(h, s.BoxSizing)
	h = styleInternHashFloat64(h, s.Top)
	h = styleInternHashFloat64(h, s.Right)
	h = styleInternHashFloat64(h, s.Bottom)
	h = styleInternHashFloat64(h, s.Left)
	h = styleInternHashBool(h, s.TopAuto)
	h = styleInternHashBool(h, s.RightAuto)
	h = styleInternHashBool(h, s.BottomAuto)
	h = styleInternHashBool(h, s.LeftAuto)
	h = styleInternHashString(h, s.FlexDirection)
	h = styleInternHashString(h, s.FlexWrap)
	h = styleInternHashString(h, s.JustifyContent)
	h = styleInternHashString(h, s.AlignItems)
	h = styleInternHashString(h, s.AlignContent)
	h = styleInternHashString(h, s.AlignSelf)
	h = styleInternHashString(h, s.JustifyItems)
	h = styleInternHashString(h, s.JustifySelf)
	h = styleInternHashFloat64(h, s.Gap)
	h = styleInternHashFloat64(h, s.RowGap)
	h = styleInternHashFloat64(h, s.ColumnGap)
	h = styleInternHashBool(h, s.ColumnGapNormal)
	h = styleInternHashInt(h, s.ColumnCount)
	h = styleInternHashFloat64(h, s.ColumnWidth)
	h = styleInternHashString(h, s.ColumnSpan)
	h = styleInternHashString(h, s.ColumnFill)
	h = styleInternHashFloat64(h, s.ColumnRuleWidth)
	h = styleInternHashString(h, s.ColumnRuleStyle)
	for _, e := range s.ColumnRuleColor {
		h = styleInternHashFloat64(h, e)
	}
	h = styleInternHashBool(h, s.ColumnRuleColorSet)
	h = styleInternHashFloat64(h, s.FlexGrow)
	h = styleInternHashFloat64(h, s.FlexShrink)
	h = styleInternHashFloat64(h, s.FlexBasis)
	h = styleInternHashFloat64(h, s.FlexBasisPercent)
	h = styleInternHashInt(h, s.FlexOrder)
	h = styleInternHashInt(h, s.ZIndex)
	h = styleInternHashBool(h, s.ZIndexSet)
	h = styleInternHashString(h, s.WritingMode)
	h = styleInternHashString(h, s.Direction)
	h = styleInternHashString(h, s.Filter)
	h = styleInternHashString(h, s.MixBlendMode)
	h = styleInternHashString(h, s.BackgroundBlendMode)
	h = styleInternHashString(h, s.Isolation)
	h = styleInternHashString(h, s.GridTemplateColumns)
	h = styleInternHashString(h, s.GridTemplateRows)
	h = styleInternHashString(h, s.GridTemplateAreas)
	h = styleInternHashString(h, s.GridArea)
	h = styleInternHashString(h, s.GridAutoFlow)
	h = styleInternHashString(h, s.GridAutoColumns)
	h = styleInternHashString(h, s.GridAutoRows)
	h = styleInternHashInt(h, s.GridColumnSpan)
	h = styleInternHashInt(h, s.GridColumnStart)
	h = styleInternHashInt(h, s.GridRowSpan)
	h = styleInternHashInt(h, s.GridRowStart)
	h = styleInternHashFloat64(h, s.Width)
	h = styleInternHashFloat64(h, s.WidthPercent)
	h = styleInternHashFloat64(h, s.Height)
	h = styleInternHashFloat64(h, s.HeightPercent)
	h = styleInternHashFloat64(h, s.MinWidth)
	h = styleInternHashFloat64(h, s.MinWidthPercent)
	h = styleInternHashBool(h, s.MinWidthSet)
	h = styleInternHashFloat64(h, s.MaxWidth)
	h = styleInternHashFloat64(h, s.MaxWidthPercent)
	h = styleInternHashFloat64(h, s.MinHeight)
	h = styleInternHashFloat64(h, s.MinHeightPercent)
	h = styleInternHashFloat64(h, s.MaxHeight)
	h = styleInternHashFloat64(h, s.MaxHeightPercent)
	h = styleInternHashString(h, s.Overflow)
	h = styleInternHashString(h, s.OverflowX)
	h = styleInternHashString(h, s.OverflowY)
	h = styleInternHashString(h, s.Visibility)
	h = styleInternHashFloat64(h, s.MarginTop)
	h = styleInternHashFloat64(h, s.MarginRight)
	h = styleInternHashFloat64(h, s.MarginBottom)
	h = styleInternHashFloat64(h, s.MarginLeft)
	h = styleInternHashBool(h, s.MarginTopAuto)
	h = styleInternHashBool(h, s.MarginBottomAuto)
	h = styleInternHashBool(h, s.MarginLeftAuto)
	h = styleInternHashBool(h, s.MarginRightAuto)
	h = styleInternHashFloat64(h, s.PaddingTop)
	h = styleInternHashFloat64(h, s.PaddingRight)
	h = styleInternHashFloat64(h, s.PaddingBottom)
	h = styleInternHashFloat64(h, s.PaddingLeft)
	h = styleInternHashBorder(h, s.BorderTop)
	h = styleInternHashBorder(h, s.BorderRight)
	h = styleInternHashBorder(h, s.BorderBottom)
	h = styleInternHashBorder(h, s.BorderLeft)
	h = styleInternHashFloat64(h, s.BorderRadius)
	h = styleInternHashFloat64(h, s.BorderRadiusPercent)
	h = styleInternHashFloat64(h, s.BorderRadiusTopLeft)
	h = styleInternHashFloat64(h, s.BorderRadiusTopRight)
	h = styleInternHashFloat64(h, s.BorderRadiusBottomRight)
	h = styleInternHashFloat64(h, s.BorderRadiusBottomLeft)
	h = styleInternHashFloat64(h, s.BorderRadiusTopLeftY)
	h = styleInternHashFloat64(h, s.BorderRadiusTopRightY)
	h = styleInternHashFloat64(h, s.BorderRadiusBottomRightY)
	h = styleInternHashFloat64(h, s.BorderRadiusBottomLeftY)
	for _, e := range s.Color {
		h = styleInternHashFloat64(h, e)
	}
	for _, e := range s.BGColor {
		h = styleInternHashFloat64(h, e)
	}
	for _, e := range s.AccentColor {
		h = styleInternHashFloat64(h, e)
	}
	h = styleInternHashBool(h, s.AccentColorSet)
	h = styleInternHashStringSlice(h, s.FontFamily)
	h = styleInternHashUint64(h, s.famHash)
	h = styleInternHashFloat64(h, s.FontSize)
	h = styleInternHashInt(h, s.FontWeight)
	h = styleInternHashBool(h, s.FontItalic)
	h = styleInternHashFloat64(h, s.LineHeight)
	h = styleInternHashFloat64(h, s.LineHeightUnitless)
	h = styleInternHashString(h, s.TextAlign)
	h = styleInternHashString(h, s.TextAlignLast)
	h = styleInternHashString(h, s.TextTransform)
	h = styleInternHashString(h, s.VerticalAlign)
	h = styleInternHashFloat64(h, s.VerticalAlignShift)
	h = styleInternHashString(h, s.WhiteSpace)
	h = styleInternHashString(h, s.WhiteSpaceCollapse)
	h = styleInternHashString(h, s.WhiteSpaceTrim)
	h = styleInternHashString(h, s.TextWrap)
	h = styleInternHashString(h, s.TextWrapMode)
	h = styleInternHashString(h, s.TextWrapStyle)
	h = styleInternHashFloat64(h, s.TabSize)
	h = styleInternHashString(h, s.Hyphens)
	h = styleInternHashString(h, s.HyphenateCharacter)
	h = styleInternHashString(h, s.TextJustify)
	h = styleInternHashString(h, s.LineBreak)
	h = styleInternHashString(h, s.OverflowWrap)
	h = styleInternHashString(h, s.WordBreak)
	h = styleInternHashString(h, s.TextDecoration)
	h = styleInternHashString(h, s.TextDecorationLine)
	for _, e := range s.TextDecorationColor {
		h = styleInternHashFloat64(h, e)
	}
	h = styleInternHashBool(h, s.TextDecorationColorSet)
	h = styleInternHashString(h, s.TextDecorationStyle)
	h = styleInternHashFloat64(h, s.TextDecorationThickness)
	h = styleInternHashFloat64(h, s.TextUnderlineOffset)
	h = styleInternHashString(h, s.TextUnderlinePosition)
	h = styleInternHashFloat64(h, s.TextShadowX)
	h = styleInternHashFloat64(h, s.TextShadowY)
	h = styleInternHashFloat64(h, s.TextShadowBlur)
	for _, e := range s.TextShadowColor {
		h = styleInternHashFloat64(h, e)
	}
	h = styleInternHashBool(h, s.TextShadowSet)
	h = styleInternHashFloat64(h, s.LetterSpacing)
	h = styleInternHashFloat64(h, s.WordSpacing)
	h = styleInternHashFloat64(h, s.TextIndent)
	h = styleInternHashString(h, s.ListStyleType)
	h = styleInternHashString(h, s.BorderCollapse)
	h = styleInternHashFloat64(h, s.BorderSpacing)
	h = styleInternHashFloat64(h, s.BorderSpacingV)
	h = styleInternHashString(h, s.TableLayout)
	h = styleInternHashString(h, s.CaptionSide)
	h = styleInternHashBool(h, s.IsReplaced)
	h = styleInternHashString(h, s.PageBreakBefore)
	h = styleInternHashString(h, s.PageBreakAfter)
	h = styleInternHashString(h, s.PageBreakInside)
	h = styleInternHashString(h, s.MarginBreak)
	h = styleInternHashString(h, s.PageName)
	h = styleInternHashInt(h, s.Orphans)
	h = styleInternHashInt(h, s.Widows)
	h = styleInternHashString(h, s.EmptyCells)
	h = styleInternHashString(h, s.ContainerType)
	h = styleInternHashString(h, s.ContainerName)
	h = styleInternHashMatrix2D(h, s.Transform)
	h = styleInternHashBool(h, s.HasTransform)
	h = styleInternHashTransformOriginSpec(h, s.TransformOrigin)
	h = styleInternHashFloat64(h, s.TranslateXPercent)
	h = styleInternHashBool(h, s.TranslateXPercentSet)
	h = styleInternHashFloat64(h, s.TranslateYPercent)
	h = styleInternHashBool(h, s.TranslateYPercentSet)
	h = styleInternHashFloat64(h, s.Opacity)
	h = styleInternHashString(h, s.Content)
	h = styleInternHashInt(h, s.GridColumnEnd)
	h = styleInternHashInt(h, s.GridRowEnd)
	h = styleInternHashFloat64(h, s.OutlineWidth)
	h = styleInternHashString(h, s.OutlineStyle)
	for _, e := range s.OutlineColor {
		h = styleInternHashFloat64(h, e)
	}
	h = styleInternHashBool(h, s.OutlineColorSet)
	h = styleInternHashFloat64(h, s.OutlineOffset)
	h = styleInternHashString(h, s.BackgroundImage)
	h = styleInternHashString(h, s.BackgroundPosX)
	h = styleInternHashString(h, s.BackgroundPosY)
	h = styleInternHashString(h, s.BackgroundSize)
	h = styleInternHashString(h, s.BackgroundRepeat)
	h = styleInternHashString(h, s.BackgroundRepeatX)
	h = styleInternHashString(h, s.BackgroundRepeatY)
	h = styleInternHashString(h, s.BackgroundRepeatBlock)
	h = styleInternHashString(h, s.BackgroundRepeatInline)
	h = styleInternHashString(h, s.BackgroundClip)
	h = styleInternHashString(h, s.BackgroundOrigin)
	h = styleInternHashString(h, s.BackgroundAttachment)
	h = styleInternHashString(h, s.BorderImageSource)
	h = styleInternHashString(h, s.BorderImageSlice)
	h = styleInternHashString(h, s.BorderImageWidth)
	h = styleInternHashString(h, s.BorderImageOutset)
	h = styleInternHashString(h, s.BorderImageRepeat)
	h = styleInternHashString(h, s.ListStylePosition)
	h = styleInternHashString(h, s.QuotesRaw)
	h = styleInternHashString(h, s.QuotesOpen)
	h = styleInternHashString(h, s.QuotesClose)
	h = styleInternHashString(h, s.CounterReset)
	h = styleInternHashString(h, s.CounterIncrement)
	h = styleInternHashString(h, s.ListStyleImage)
	h = styleInternHashFloat64(h, s.BoxShadowX)
	h = styleInternHashFloat64(h, s.BoxShadowY)
	h = styleInternHashFloat64(h, s.BoxShadowBlur)
	h = styleInternHashFloat64(h, s.BoxShadowSpread)
	for _, e := range s.BoxShadowColor {
		h = styleInternHashFloat64(h, e)
	}
	h = styleInternHashBool(h, s.BoxShadowSet)
	h = styleInternHashBool(h, s.BoxShadowInset)
	h = styleInternHashString(h, s.BoxShadowRaw)
	for _, e := range s.Fill {
		h = styleInternHashFloat64(h, e)
	}
	h = styleInternHashBool(h, s.FillSet)
	h = styleInternHashFloat64(h, s.FillOpacity)
	for _, e := range s.Stroke {
		h = styleInternHashFloat64(h, e)
	}
	h = styleInternHashBool(h, s.StrokeSet)
	h = styleInternHashFloat64(h, s.StrokeWidth)
	h = styleInternHashBool(h, s.StrokeWidthSet)
	h = styleInternHashFloat64(h, s.StrokeOpacity)
	h = styleInternHashFloat64Slice(h, s.StrokeDashArray)
	h = styleInternHashFloat64(h, s.StrokeDashOffset)
	h = styleInternHashString(h, s.StrokeLineCap)
	h = styleInternHashString(h, s.StrokeLineJoin)
	h = styleInternHashFloat64(h, s.StrokeMiterLimit)
	h = styleInternHashString(h, s.TextOverflow)
	h = styleInternHashInt(h, s.LineClamp)
	h = styleInternHashInt(h, s.MaxLines)
	h = styleInternHashString(h, s.MarginTrim)
	h = styleInternHashString(h, s.BoxDecorationBreak)
	h = styleInternHashString(h, s.TextDecorationSkipInk)
	h = styleInternHashFloat64(h, s.OverflowClipMarginTop)
	h = styleInternHashFloat64(h, s.OverflowClipMarginRight)
	h = styleInternHashFloat64(h, s.OverflowClipMarginBottom)
	h = styleInternHashFloat64(h, s.OverflowClipMarginLeft)
	h = styleInternHashString(h, s.Contain)
	h = styleInternHashFloat64(h, s.ContainIntrinsicWidth)
	h = styleInternHashFloat64(h, s.ContainIntrinsicHeight)
	h = styleInternHashFloat64(h, s.ContainIntrinsicBlockSize)
	h = styleInternHashFloat64(h, s.ContainIntrinsicInlineSize)
	h = styleInternHashString(h, s.ContentVisibility)
	h = styleInternHashString(h, s.ColorAdjust)
	h = styleInternHashString(h, s.ForcedColorAdjust)
	h = styleInternHashString(h, s.ColorScheme)
	h = styleInternHashString(h, s.DynamicRangeLimit)
	h = styleInternHashString(h, s.FontLanguageOverride)
	h = styleInternHashString(h, s.FontOpticalSizing)
	h = styleInternHashString(h, s.FontPalette)
	h = styleInternHashString(h, s.FontVariationSettings)
	h = styleInternHashString(h, s.ImageOrientation)
	h = styleInternHashFloat64(h, s.ImageOrientationAngle)
	h = styleInternHashString(h, s.ImageResolution)
	h = styleInternHashFloat64(h, s.ImageResolutionDPI)
	h = styleInternHashString(h, s.ObjectViewBox)
	h = styleInternHashString(h, s.TextCombineUpright)
	h = styleInternHashFloat64(h, s.TextDecorationInset)
	h = styleInternHashString(h, s.TextDecorationSkip)
	h = styleInternHashString(h, s.TextDecorationSkipBox)
	h = styleInternHashString(h, s.TextDecorationSkipSelf)
	h = styleInternHashString(h, s.TextDecorationSkipSpaces)
	h = styleInternHashString(h, s.TextOrientation)
	h = styleInternHashString(h, s.UnicodeBidi)
	h = styleInternHashStringMap(h, s.CustomProps)

	return h
}

// styleInternFields lists every field styleInternEqual and
// styleInternFingerprint cover, in declaration order.
func styleInternFields() []string {
	return []string{
		"Display",
		"IsWebkitBox",
		"Position",
		"Float",
		"Clear",
		"BoxSizing",
		"Top",
		"Right",
		"Bottom",
		"Left",
		"TopAuto",
		"RightAuto",
		"BottomAuto",
		"LeftAuto",
		"FlexDirection",
		"FlexWrap",
		"JustifyContent",
		"AlignItems",
		"AlignContent",
		"AlignSelf",
		"JustifyItems",
		"JustifySelf",
		"Gap",
		"RowGap",
		"ColumnGap",
		"ColumnGapNormal",
		"ColumnCount",
		"ColumnWidth",
		"ColumnSpan",
		"ColumnFill",
		"ColumnRuleWidth",
		"ColumnRuleStyle",
		"ColumnRuleColor",
		"ColumnRuleColorSet",
		"FlexGrow",
		"FlexShrink",
		"FlexBasis",
		"FlexBasisPercent",
		"FlexOrder",
		"ZIndex",
		"ZIndexSet",
		"WritingMode",
		"Direction",
		"Filter",
		"MixBlendMode",
		"BackgroundBlendMode",
		"Isolation",
		"GridTemplateColumns",
		"GridTemplateRows",
		"GridTemplateAreas",
		"GridArea",
		"GridAutoFlow",
		"GridAutoColumns",
		"GridAutoRows",
		"GridColumnSpan",
		"GridColumnStart",
		"GridRowSpan",
		"GridRowStart",
		"Width",
		"WidthPercent",
		"Height",
		"HeightPercent",
		"MinWidth",
		"MinWidthPercent",
		"MinWidthSet",
		"MaxWidth",
		"MaxWidthPercent",
		"MinHeight",
		"MinHeightPercent",
		"MaxHeight",
		"MaxHeightPercent",
		"Overflow",
		"OverflowX",
		"OverflowY",
		"Visibility",
		"MarginTop",
		"MarginRight",
		"MarginBottom",
		"MarginLeft",
		"MarginTopAuto",
		"MarginBottomAuto",
		"MarginLeftAuto",
		"MarginRightAuto",
		"PaddingTop",
		"PaddingRight",
		"PaddingBottom",
		"PaddingLeft",
		"BorderTop",
		"BorderRight",
		"BorderBottom",
		"BorderLeft",
		"BorderRadius",
		"BorderRadiusPercent",
		"BorderRadiusTopLeft",
		"BorderRadiusTopRight",
		"BorderRadiusBottomRight",
		"BorderRadiusBottomLeft",
		"BorderRadiusTopLeftY",
		"BorderRadiusTopRightY",
		"BorderRadiusBottomRightY",
		"BorderRadiusBottomLeftY",
		"Color",
		"BGColor",
		"AccentColor",
		"AccentColorSet",
		"FontFamily",
		"famHash",
		"FontSize",
		"FontWeight",
		"FontItalic",
		"LineHeight",
		"LineHeightUnitless",
		"TextAlign",
		"TextAlignLast",
		"TextTransform",
		"VerticalAlign",
		"VerticalAlignShift",
		"WhiteSpace",
		"WhiteSpaceCollapse",
		"WhiteSpaceTrim",
		"TextWrap",
		"TextWrapMode",
		"TextWrapStyle",
		"TabSize",
		"Hyphens",
		"HyphenateCharacter",
		"TextJustify",
		"LineBreak",
		"OverflowWrap",
		"WordBreak",
		"TextDecoration",
		"TextDecorationLine",
		"TextDecorationColor",
		"TextDecorationColorSet",
		"TextDecorationStyle",
		"TextDecorationThickness",
		"TextUnderlineOffset",
		"TextUnderlinePosition",
		"TextShadowX",
		"TextShadowY",
		"TextShadowBlur",
		"TextShadowColor",
		"TextShadowSet",
		"LetterSpacing",
		"WordSpacing",
		"TextIndent",
		"ListStyleType",
		"BorderCollapse",
		"BorderSpacing",
		"BorderSpacingV",
		"TableLayout",
		"CaptionSide",
		"IsReplaced",
		"PageBreakBefore",
		"PageBreakAfter",
		"PageBreakInside",
		"MarginBreak",
		"PageName",
		"Orphans",
		"Widows",
		"EmptyCells",
		"ContainerType",
		"ContainerName",
		"Transform",
		"HasTransform",
		"TransformOrigin",
		"TranslateXPercent",
		"TranslateXPercentSet",
		"TranslateYPercent",
		"TranslateYPercentSet",
		"Opacity",
		"Content",
		"GridColumnEnd",
		"GridRowEnd",
		"OutlineWidth",
		"OutlineStyle",
		"OutlineColor",
		"OutlineColorSet",
		"OutlineOffset",
		"BackgroundImage",
		"BackgroundPosX",
		"BackgroundPosY",
		"BackgroundSize",
		"BackgroundRepeat",
		"BackgroundRepeatX",
		"BackgroundRepeatY",
		"BackgroundRepeatBlock",
		"BackgroundRepeatInline",
		"BackgroundClip",
		"BackgroundOrigin",
		"BackgroundAttachment",
		"BorderImageSource",
		"BorderImageSlice",
		"BorderImageWidth",
		"BorderImageOutset",
		"BorderImageRepeat",
		"ListStylePosition",
		"QuotesRaw",
		"QuotesOpen",
		"QuotesClose",
		"CounterReset",
		"CounterIncrement",
		"ListStyleImage",
		"BoxShadowX",
		"BoxShadowY",
		"BoxShadowBlur",
		"BoxShadowSpread",
		"BoxShadowColor",
		"BoxShadowSet",
		"BoxShadowInset",
		"BoxShadowRaw",
		"Fill",
		"FillSet",
		"FillOpacity",
		"Stroke",
		"StrokeSet",
		"StrokeWidth",
		"StrokeWidthSet",
		"StrokeOpacity",
		"StrokeDashArray",
		"StrokeDashOffset",
		"StrokeLineCap",
		"StrokeLineJoin",
		"StrokeMiterLimit",
		"TextOverflow",
		"LineClamp",
		"MaxLines",
		"MarginTrim",
		"BoxDecorationBreak",
		"TextDecorationSkipInk",
		"OverflowClipMarginTop",
		"OverflowClipMarginRight",
		"OverflowClipMarginBottom",
		"OverflowClipMarginLeft",
		"Contain",
		"ContainIntrinsicWidth",
		"ContainIntrinsicHeight",
		"ContainIntrinsicBlockSize",
		"ContainIntrinsicInlineSize",
		"ContentVisibility",
		"ColorAdjust",
		"ForcedColorAdjust",
		"ColorScheme",
		"DynamicRangeLimit",
		"FontLanguageOverride",
		"FontOpticalSizing",
		"FontPalette",
		"FontVariationSettings",
		"ImageOrientation",
		"ImageOrientationAngle",
		"ImageResolution",
		"ImageResolutionDPI",
		"ObjectViewBox",
		"TextCombineUpright",
		"TextDecorationInset",
		"TextDecorationSkip",
		"TextDecorationSkipBox",
		"TextDecorationSkipSelf",
		"TextDecorationSkipSpaces",
		"TextOrientation",
		"UnicodeBidi",
		"CustomProps",
	}
}

func styleInternHashMatrix2D(h uint64, v Matrix2D) uint64 {
	h = styleInternHashFloat64(h, v.A)
	h = styleInternHashFloat64(h, v.B)
	h = styleInternHashFloat64(h, v.C)
	h = styleInternHashFloat64(h, v.D)
	h = styleInternHashFloat64(h, v.E)
	h = styleInternHashFloat64(h, v.F)

	return h
}

func styleInternHashBorder(h uint64, v border) uint64 {
	h = styleInternHashFloat64(h, v.Width)
	h = styleInternHashFloat64(h, v.PaintWidth)
	h = styleInternHashString(h, v.Style)
	for _, e := range v.Color {
		h = styleInternHashFloat64(h, e)
	}

	return h
}

func styleInternHashTransformOriginSpec(h uint64, v transformOriginSpec) uint64 {
	h = styleInternHashFloat64(h, v.X)
	h = styleInternHashFloat64(h, v.Y)
	h = styleInternHashBool(h, v.XPercent)
	h = styleInternHashBool(h, v.YPercent)

	return h
}
