package chrome_test

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chinmay-sawant/gowkhtmltopdf/internal/convert"
	"github.com/chinmay-sawant/gowkhtmltopdf/internal/pdf"
	"github.com/chinmay-sawant/gowkhtmltopdf/internal/settings"
)

const chromePDFOutputDir = "../chrome/pdf"

// TestChromeCasePDFOutputs renders every Chrome case into a local PDF so the
// current product output can be inspected alongside the case HTML. The PDF
// is intentionally not a pass/fail oracle for layout geometry. The focused
// layout tests own those assertions, including the cases currently blocked by
// known engine gaps.
func TestChromeCasePDFOutputs(t *testing.T) {
	t.Parallel()

	manifest := readManifest(t)

	if err := os.MkdirAll(chromePDFOutputDir, 0o755); err != nil {
		t.Fatalf("create PDF output directory: %v", err)
	}

	for _, item := range manifest.Cases {
		writeChromeCasePDF(t, item)
	}
}

func writeChromeCasePDF(t *testing.T, item manifestCase) {
	t.Helper()

	var output bytes.Buffer

	request := chromeCasePDFRequest(t, item, &output)

	if err := convert.Run(t.Context(), request, io.Discard, nil); err != nil {
		t.Fatalf("convert case %q: %v", item.ID, err)
	}

	document, err := pdf.ParseSemantic(output.Bytes())
	if err != nil {
		t.Fatalf("parse generated PDF for %q: %v", item.ID, err)
	}

	if document.PageCount() == 0 {
		t.Fatalf("generated PDF for %q has no pages", item.ID)
	}

	if strings.HasPrefix(item.ID, "legacy-") && strings.TrimSpace(document.DocumentText()) == "" {
		t.Fatalf("legacy case %q generated a PDF with no visible text", item.ID)
	}

	fixtureName := strings.TrimSuffix(filepath.Base(item.Fixture), filepath.Ext(item.Fixture))
	outputPath := filepath.Join(chromePDFOutputDir, fixtureName+".pdf")

	if err := os.WriteFile(outputPath, output.Bytes(), 0o600); err != nil {
		t.Fatalf("write %s: %v", outputPath, err)
	}

	t.Logf("wrote %s (%d pages)", outputPath, document.PageCount())
}

// chromeCasePDFRequest builds the PDF request shared by the output test and
// the allocation benchmark: local-file access enabled, the case HTML as a
// single page object, and the generated bytes written to output.
func chromeCasePDFRequest(tb testing.TB, item manifestCase, output *bytes.Buffer) *convert.Request {
	tb.Helper()

	fixturePath, err := filepath.Abs(item.Fixture)
	if err != nil {
		tb.Fatalf("resolve fixture path: %v", err)
	}

	if _, err := os.Stat(fixturePath); err != nil {
		tb.Fatalf("stat fixture %q: %v", item.Fixture, err)
	}

	global := settings.DefaultPdfGlobal()
	global.Title = item.ID
	global.Load.EnableLocalFileAccess = true

	object := settings.DefaultPdfObject()
	object.Page = fixturePath
	object.Load.BlockLocalFileAccess = false

	return convert.NewPDFRequest(
		global,
		[]settings.PdfObject{object},
		output,
		nil,
	)
}
